"""Generate the README's command reference from the installed tools' own help (maintenance: README).

    python3 scripts/readme_reference.py --check   # exit 1, naming each tool, if README.md differs
    python3 scripts/readme_reference.py --write   # rewrite the reference block in README.md

The tools are every executable file in tools/bin/, the set the image installs to /opt/timelike/bin
(image/Dockerfile: COPY tools/bin/). Each section is the tool's `--help`, verbatim: its summary,
synopsis, every flag with its meaning, and its exit codes, all written by agentio from the tool's own
definition (contract rule 6). Nothing is hand-written, so a flag cannot drift from the tool, as the
announcement cannot (feature 007).

`--help` is read at COLUMNS=1000, because the contract cuts long lines at COLUMNS (rule 13), and with
PYTHONPATH at tools/agentio and a throwaway scratch root, so the output does not depend on the caller's
terminal, home or session. `--agent-info` is not read: `timelike --agent-info` needs the image's build
stamp, and `--help` already carries the summary.
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
TOOLS = REPO / "tools" / "bin"
AGENTIO = REPO / "tools" / "agentio"
README = REPO / "README.md"
BEGIN = "<!-- BEGIN command reference: generated by scripts/readme_reference.py --write; do not edit -->"
END = "<!-- END command reference -->"


def installed_tools(tools: Path = TOOLS) -> list[str]:
    return sorted(p.name for p in tools.iterdir() if p.is_file() and os.access(p, os.X_OK))


def help_of(name: str, tools: Path = TOOLS) -> str:
    with tempfile.TemporaryDirectory() as tmp:
        env = {
            "PATH": os.environ.get("PATH", "/usr/bin:/bin"),
            "HOME": tmp,
            "PYTHONPATH": str(AGENTIO),
            "TIMELIKE_SCRATCH_ROOT": str(Path(tmp) / "scratch"),
            "COLUMNS": "1000",
            "LC_ALL": "C.UTF-8",
        }
        r = subprocess.run(
            [sys.executable, str(tools / name), "--help"],
            env=env,
            cwd=tmp,
            stdin=subprocess.DEVNULL,
            capture_output=True,
            text=True,
            timeout=30,
            check=False,
        )
    if r.returncode != 0:
        raise SystemExit(f"error: {name} --help exited {r.returncode}: {r.stderr.strip()}")
    return r.stdout.rstrip("\n")


def section(name: str, text: str) -> str:
    return f"### `{name}`\n\n```text\n{text}\n```\n"


def reference(tools: Path = TOOLS) -> str:
    body = "\n".join(section(n, help_of(n, tools)) for n in installed_tools(tools))
    return f"{BEGIN}\n\n{body}\n{END}"


def split(readme: str) -> tuple[str, str, str]:
    """README as (before, the generated block, after); refuses a README without exactly one block."""
    if readme.count(BEGIN) != 1 or readme.count(END) != 1 or readme.index(BEGIN) > readme.index(END):
        raise SystemExit(f"error: {README.name} must hold exactly one block between the reference markers")
    a = readme.index(BEGIN)
    b = readme.index(END) + len(END)
    return readme[:a], readme[a:b], readme[b:]


def sections_of(block: str) -> dict[str, str]:
    """Each tool's section in a reference block, by tool name."""
    out: dict[str, str] = {}
    for part in block.split("\n### `")[1:]:
        name = part.split("`", 1)[0]
        out[name] = "### `" + part.split(f"\n{END}", 1)[0].rstrip("\n") + "\n"
    return out


def differences(readme: str, ref: str | None = None) -> list[str]:
    """One line per tool whose section is missing, extra or not what its --help produces now.
    `ref` is a reference already generated (the tests generate it once); by default, generate it."""
    ref = reference() if ref is None else ref
    have = sections_of(split(readme)[1])
    want = sections_of(ref)
    out = [f"{n}: missing from the README's reference" for n in want if n not in have]
    out += [f"{n}: in the reference but not installed" for n in have if n not in want]
    out += [f"{n}: differs from `{n} --help`" for n in want if n in have and have[n] != want[n]]
    if not out and split(readme)[1] != ref:
        out.append("the reference block differs (order or spacing)")
    return out


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="the README's command reference, from the tools' own --help")
    g = p.add_mutually_exclusive_group(required=True)
    g.add_argument("--check", action="store_true", help="exit 1 if README.md differs; name each tool")
    g.add_argument("--write", action="store_true", help="rewrite the reference block in README.md")
    a = p.parse_args(argv)
    readme = README.read_text(encoding="utf-8")
    if a.write:
        before, _, after = split(readme)
        README.write_text(before + reference() + after, encoding="utf-8")
        print(f"readme reference: written, {len(installed_tools())} tools")
        return 0
    diffs = differences(readme)
    for d in diffs:
        print(f"readme reference: {d}")
    if diffs:
        print("readme reference: regenerate with `python3 scripts/readme_reference.py --write`")
        return 1
    print(f"readme reference: current, {len(installed_tools())} tools")
    return 0


if __name__ == "__main__":
    sys.exit(main())
