"""scan/denylist.py — the publish deny-list over the tracked tree (maintenance send, publish redaction).

Every check here must be seen failing (cross-stack P005). The lists and the plants are built at run
time: these tests use synthetic entries of each kind the real list holds (a host name, a path with an
alternation, a personal name with a character class, an address), so this file commits no real
pattern and no real string. One test reads the REAL list when it is available (the mentor's lane and
the code workspace, never a public clone) and checks the pre-redaction tree against the mentor's own
counts; anywhere else it skips, saying why.
"""

from __future__ import annotations

import io
import json
import os
import subprocess
import sys
import tarfile
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "scan"))
import denylist

REPO = Path(__file__).resolve().parents[2]

# Synthetic entries, one per kind. Their plants are generated by the module from these regexes.
KINDS = {
    "T1": "kestrel-?box",  # a host name
    "T2": "/srv/(alpha|beta)/",  # an absolute path, with an alternation
    "T3": "[jJ]ane +Qux",  # a personal name, with a character class
    "T4": "someone@example[.]invalid",  # an address
}


def write_list(tmp_path: Path, entries: dict[str, str], extra: str = "") -> Path:
    p = tmp_path / "denylist.txt"
    body = "# synthetic deny-list, built by the test\n\n" + "".join(f"{k}\t{v}\n" for k, v in entries.items())
    p.write_text(body + extra, encoding="utf-8")
    return p


def tar_of(files: dict[str, str], links: dict[str, str] | None = None) -> tuple[io.BytesIO, int]:
    buf = io.BytesIO()
    with tarfile.open(fileobj=buf, mode="w") as tar:
        for name, text in files.items():
            data = text.encode()
            info = tarfile.TarInfo(name)
            info.size = len(data)
            tar.addfile(info, io.BytesIO(data))
        for name, target in (links or {}).items():
            info = tarfile.TarInfo(name)
            info.type = tarfile.SYMTYPE
            info.linkname = target
            tar.addfile(info)
    buf.seek(0)
    return buf, len(files) + len(links or {})


def plants() -> dict[str, str]:
    return {k: denylist.plant_for(denylist.Entry(k, v)) for k, v in KINDS.items()}


def clean_tree() -> dict[str, str]:
    return {"README.md": "# a project\n\nnothing to see\n", "src/a.py": "x = 1\n"}


def test_a_clean_tree_passes_and_every_entry_was_checked(tmp_path: Path) -> None:
    tar, n = tar_of(clean_tree())
    r = denylist.run(write_list(tmp_path, KINDS), "the test list", tar, n)
    assert (r.state, r.exit_code()) == ("pass", 0)
    assert r.entries == list(KINDS)
    assert r.files_checked == 2
    assert all(c == {"files": 0, "lines": 0, "matches": 0} for c in r.counts.values())


@pytest.mark.parametrize("kind", sorted(KINDS))
def test_each_kind_planted_fails_by_id_and_file_line_never_the_text(kind: str, tmp_path: Path) -> None:
    plant = plants()[kind]
    files = {**clean_tree(), "docs/notes.md": f"line one\nsee {plant} for details\nline three\n"}
    tar, n = tar_of(files)
    out = tmp_path / "out.json"
    lst = write_list(tmp_path, KINDS)
    tar_path = tmp_path / "tree.tar"
    tar_path.write_bytes(tar.getvalue())
    rc = denylist.main(
        ["--list", str(lst), "--tar", str(tar_path), "--expect-files", str(n), "--out", str(out)]
    )
    assert rc == 1
    doc = json.loads(out.read_text())
    assert doc["state"] == "fail"
    assert doc["findings"] == [{"id": kind, "file": "docs/notes.md", "line": 2}]
    assert doc["counts"][kind] == {"files": 1, "lines": 1, "matches": 1}
    # the matched text and the pattern appear in no output: the report names ids and places only
    assert plant.lower() not in out.read_text().lower()
    assert KINDS[kind] not in out.read_text()


def test_the_rendered_report_names_ids_and_places_only(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    p = plants()
    files = {**clean_tree(), "a.txt": f"{p['T1']} and {p['T4']}\n", "b/c.txt": f"x\n{p['T2']}\n{p['T2']}\n"}
    tar_path = tmp_path / "tree.tar"
    tar, n = tar_of(files)
    tar_path.write_bytes(tar.getvalue())
    rc = denylist.main(
        ["--list", str(write_list(tmp_path, KINDS)), "--tar", str(tar_path), "--expect-files", str(n)]
    )
    text = capsys.readouterr().out
    assert rc == 1
    assert (
        text.splitlines()[0] == "publish deny-list [tracked tree]: FAIL — 4 tracked lines match the deny-list"
    )
    assert {"FAIL T1 a.txt:1", "FAIL T4 a.txt:1", "FAIL T2 b/c.txt:2", "FAIL T2 b/c.txt:3"} <= set(
        text.splitlines()
    )
    assert text.splitlines()[-1] == "per id: T1 1/1, T2 1/2, T3 0/0, T4 1/1"
    for plant in p.values():
        assert plant.lower() not in text.lower()


def test_two_matches_on_one_line_count_as_one_line_two_matches(tmp_path: Path) -> None:
    plant = plants()["T2"]
    tar, n = tar_of({"x.md": f"{plant}a and {plant}b\n"})
    r = denylist.run(write_list(tmp_path, KINDS), "l", tar, n)
    assert r.counts["T2"] == {"files": 1, "lines": 1, "matches": 2}


def test_case_is_ignored(tmp_path: Path) -> None:
    tar, n = tar_of({"x.md": plants()["T1"].upper() + "\n"})
    assert denylist.run(write_list(tmp_path, KINDS), "l", tar, n).state == "fail"


def test_a_symlink_target_is_checked_too(tmp_path: Path) -> None:
    tar, n = tar_of(clean_tree(), links={"link": plants()["T2"] + "file"})
    r = denylist.run(write_list(tmp_path, KINDS), "l", tar, n)
    assert r.state == "fail"
    assert r.findings == [{"id": "T2", "file": "link", "line": "symlink target"}]


def test_no_list_is_unknown_never_pass_and_does_not_fail(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    tar, _n = tar_of(clean_tree())
    tar_path = tmp_path / "tree.tar"
    tar_path.write_bytes(tar.getvalue())
    rc = denylist.main(
        ["--list", str(tmp_path / "absent.txt"), "--list-label", "../bridge/x", "--tar", str(tar_path)]
    )
    out = capsys.readouterr().out
    assert rc == 0
    assert out.splitlines() == [
        "publish deny-list [tracked tree]: unknown — no deny-list available (../bridge/x is not there);"
        " nothing was checked"
    ]
    assert "PASS" not in out and "pass" not in out.split("—")[0]


def test_the_list_path_comes_from_the_environment(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    tar, n = tar_of({"x.md": plants()["T3"] + "\n"})
    tar_path = tmp_path / "tree.tar"
    tar_path.write_bytes(tar.getvalue())
    monkeypatch.setenv(denylist.LIST_ENV, str(write_list(tmp_path, KINDS)))
    assert denylist.main(["--tar", str(tar_path), "--expect-files", str(n)]) == 1


@pytest.mark.parametrize(
    ("body", "words"),
    [
        ("# only comments\n\n", "has no entries"),
        ("T1 no tab here\n", "line 1 is not <id><TAB><regex>"),
        ("T1\t\n", "line 1 is not <id><TAB><regex>"),
        ("1bad\tx\n", "line 1 is not <id><TAB><regex>"),
        ("T1\tabc\nT1\tdef\n", "line 2 repeats id T1"),
        ("T9\tab(c\n", "entry T9 is not a valid extended regex"),
    ],
)
def test_an_unusable_list_is_an_error_naming_the_line_or_id_never_the_pattern(
    body: str, words: str, tmp_path: Path
) -> None:
    p = tmp_path / "l.txt"
    p.write_text(body, encoding="utf-8")
    tar, n = tar_of(clean_tree())
    r = denylist.run(p, "l", tar, n)
    assert (r.state, r.exit_code()) == ("error", 2)
    assert words in r.reason
    for frag in ("abc", "def", "ab(c", "no tab here"):
        assert frag not in r.reason


def test_an_archive_that_leaves_files_out_is_an_error(tmp_path: Path) -> None:
    tar, n = tar_of(clean_tree())
    r = denylist.run(write_list(tmp_path, KINDS), "l", tar, n + 1)
    assert r.state == "error"
    assert "HEAD tracks 3" in r.reason


def test_an_unsafe_archive_path_is_an_error(tmp_path: Path) -> None:
    tar, n = tar_of({"../escape.txt": "x\n"})
    r = denylist.run(write_list(tmp_path, KINDS), "l", tar, n)
    assert r.state == "error"
    assert "unsafe path" in r.reason


def test_a_member_type_it_cannot_read_is_an_error(tmp_path: Path) -> None:
    buf = io.BytesIO()
    with tarfile.open(fileobj=buf, mode="w") as tar:
        info = tarfile.TarInfo("fifo")
        info.type = tarfile.FIFOTYPE
        tar.addfile(info)
    buf.seek(0)
    r = denylist.run(write_list(tmp_path, KINDS), "l", buf, 1)
    assert r.state == "error"
    assert "cannot read" in r.reason


def test_a_tree_that_is_not_a_tar_is_an_error(tmp_path: Path) -> None:
    r = denylist.run(write_list(tmp_path, KINDS), "l", io.BytesIO(b"not a tar at all" * 64), None)
    assert r.state == "error"


# ── the self-test: the check must see every entry before it may pass a tree ─────────────────────


def test_the_self_test_errors_when_the_matcher_cannot_see_an_entry(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A broken matcher must never pass a tree: the planted line goes unseen, and that is an error."""
    monkeypatch.setattr(denylist, "match_lines", lambda entry, path: ([], 0))
    tar, n = tar_of(clean_tree())
    r = denylist.run(write_list(tmp_path, KINDS), "l", tar, n)
    assert r.state == "error"
    assert "the check did not see it" in r.reason


@pytest.mark.parametrize(
    "pattern",
    [
        "kestrel-?box",
        "/srv/(alpha|beta)/",
        "[jJ]ane +Qux",
        "a.b",
        "x[^y]z",
        "[0-9]{3}-[a-c]+",
        "x\\sy\\w",
        "^start",
        "end$",
    ],
)
def test_a_plant_is_built_from_the_regex_and_matches_it(pattern: str) -> None:
    e = denylist.Entry("T", pattern)
    plant = denylist.plant_for(e)
    assert plant
    assert denylist.match_text(e, plant + "\n")


# \d is not ERE (GNU grep reads it as a literal d): no plant from Python's reading of it matches
@pytest.mark.parametrize("pattern", ["(a)\\1", "(?=x)", "\\d+"])
def test_a_construct_the_self_test_cannot_plant_is_an_error(pattern: str) -> None:
    with pytest.raises(denylist.ListError, match="self-test"):
        denylist.plant_for(denylist.Entry("T", pattern))


def test_the_report_json_shape(tmp_path: Path) -> None:
    tar, n = tar_of(clean_tree())
    doc = denylist.run(write_list(tmp_path, KINDS), "l", tar, n).doc()
    assert set(doc) == {"check", "state", "reason", "entries", "files_checked", "counts", "findings"}


def test_the_cli_reads_stdin(tmp_path: Path) -> None:
    tar, n = tar_of({**clean_tree(), "x.md": plants()["T4"] + "\n"})
    r = subprocess.run(
        [
            sys.executable,
            "-I",
            str(REPO / "scan" / "denylist.py"),
            "--list",
            str(write_list(tmp_path, KINDS)),
            "--expect-files",
            str(n),
        ],
        input=tar.getvalue(),
        capture_output=True,
        check=False,
    )
    assert r.returncode == 1
    assert b"FAIL T4 x.md:1" in r.stdout


# ── the real list, where it is available ────────────────────────────────────────────────────────

REAL_LIST = Path(os.environ.get(denylist.LIST_ENV) or REPO.parent / "bridge" / "publish-denylist.txt")
PRE_REDACTION = "3c10d11"
# The mentor's counts over `git ls-files` at that commit (the maintenance send's table): files/matches.
MENTOR_COUNTS = {
    "P1": (3, 4),
    "P2": (5, 12),
    "P3": (0, 0),
    "P4": (0, 0),
    "P5": (0, 0),
    "P6": (6, 6),
    "P7": (3, 3),
}


def _git(*args: str) -> subprocess.CompletedProcess[bytes]:
    return subprocess.run(["git", "-C", str(REPO), *args], capture_output=True, check=False)


def test_the_real_list_fails_the_pre_redaction_tree_with_the_mentors_counts() -> None:
    if not REAL_LIST.is_file():
        pytest.skip(f"no deny-list here ({REAL_LIST.name} absent): the check reports unknown, by design")
    if _git("cat-file", "-e", f"{PRE_REDACTION}^{{commit}}").returncode != 0:
        pytest.skip(f"{PRE_REDACTION} is not in this clone's history")
    tar = _git("archive", PRE_REDACTION)
    n = len(_git("ls-tree", "-r", PRE_REDACTION, "--name-only").stdout.splitlines())
    r = denylist.run(REAL_LIST, "the real list", io.BytesIO(tar.stdout), n)
    assert r.state == "fail"
    assert {k: (v["files"], v["matches"]) for k, v in r.counts.items()} == MENTOR_COUNTS


@pytest.mark.parametrize("make_list", ["absent", "malformed"])
def test_the_cli_reads_all_of_stdin_on_every_path(make_list: str, tmp_path: Path) -> None:
    """With no list (or a bad one) nothing is checked, but the writer of the pipe must not be killed:
    under scan.sh's pipefail, `git archive`'s SIGPIPE would fail the scan (exit 141)."""
    lst = tmp_path / "l.txt"
    if make_list == "malformed":
        lst.write_text("no tab\n", encoding="utf-8")
    script = (
        f"head -c 4000000 /dev/zero | {sys.executable} -I {REPO / 'scan' / 'denylist.py'} --list {lst}; "
        'echo "rcs=${PIPESTATUS[*]}"'
    )
    r = subprocess.run(["bash", "-c", script], capture_output=True, text=True, check=False)
    want = "0 0" if make_list == "absent" else "0 2"
    assert f"rcs={want}" in r.stdout, r.stdout
